# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "raring32"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/20130914/raring-server-cloudimg-i386-vagrant-disk1.box"
  config.vm.provision :shell, :path => "Vagrantbootstrap.sh"
  config.vm.network :forwarded_port, host: 10080, guest: 80
  config.vm.network :forwarded_port, host: 18000, guest: 8000
end
